name: TechMarket CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    uses: ./.github/workflows/templates/template_build.yml
    with:
      node_version: "20"
      image_name: "techmarket-app"

  test:
    needs: build
    uses: ./.github/workflows/templates/template_test.yml
    with:
      node_version: "20"

  push-ecr:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: techmarket-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: push-ecr
    uses: ./.github/workflows/templates/template_deploy.yml
    with:
      cluster_name: "techmarket-cluster"
      strategy: "rolling"
