name: Remediación Automática (Rollback)

on:
  repository_dispatch:
    types: [trigger-rollback]
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Recibiendo Alarma de AWS CloudWatch
        run: |
          echo "🚨 ALARMA DETECTADA: Tasa de errores 5XX superó el umbral."
          echo "Iniciando proceso de remediación automática..."

      - name: Configurar Kubeconfig (Simulado)
        run: |
          echo "Configurando credenciales del clúster EKS..."
          echo "✅ Conexión al clúster 'techmarket-cluster' establecida."

      - name: Ejecutar Rollback al entorno Blue
        run: |
          echo "Ejecutando comando: kubectl rollout undo deployment/techmarket-orders-blue --namespace=default"
          echo "Haciendo rollback a la versión anterior estable (Blue)..."
          sleep 5
          echo "✅ Rollback completado."

      - name: Verificar salud del servicio y Cambio de Tráfico
        run: |
          echo "Esperando que los pods estabilicen..."
          sleep 5
          echo "Ejecutando healthcheck: curl -f http://techmarket-alb/health"
          echo "Estado HTTP: 200 OK"
          echo "Cambiando peso del tráfico en el ALB: 100% a Blue, 0% a Green."
          echo "🚀 SERVICIO RESTAURADO CON ÉXITO. Tiempo de inactividad mitigado."
